version: 0.0
files:
  - source: /
    destination: /home/ec2-user/app

hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
      timeout: 60
      runas: root
    - location: scripts/set_permissions.sh
      timeout: 60
      runas: root

  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 60
      runas: root
