version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/scripts/
hooks:
  AfterInstall:
    - location: scripts/set_permissions.sh
    - location: scripts/install_dependencies.sh
  ApplicationStart:
    - location: scripts/start_server.sh
