version: 0.0
os: linux

files:
  - source: Web-Application-Deploy/
    destination: /home/ec2-user/myapp
    overwrite: yes

hooks:
  BeforeInstall:
    - location: scripts/make_executable.sh
      timeout: 60
      runas: ec2-user

  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user

  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 60
      runas: ec2-user
