version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/app

hooks:
  AfterInstall:
    - location: scripts/set_permissions.sh
      timeout: 300
      runas: root
      interpreter: ["/bin/bash"]

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
      interpreter: ["/bin/bash"]

  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
      interpreter: ["/bin/bash"]