version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade awscli

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 648908580279.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - echo "Build started on `date`"
      - echo "Building the Docker image..."
      - docker build -t dev-env .
      - docker tag dev-env:latest 648908580279.dkr.ecr.ap-south-1.amazonaws.com/dev-env:latest
      - docker push 648908580279.dkr.ecr.ap-south-1.amazonaws.com/dev-env:latest

  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Triggering deployment to EC2..."
      - |
        INSTANCE_ID=$(aws ec2 describe-instances \
          --filters "Name=tag:Name,Values=dev-AppServer" \
          --query "Reservations[*].Instances[*].InstanceId" \
          --output text --region ap-south-1)
        echo "Found instance: $INSTANCE_ID"
        if [ -z "$INSTANCE_ID" ]; then
          echo "❌ ERROR: No EC2 instance found with tag Name=dev-AppServer"
          exit 1
        fi
        aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --comment "Deploying latest Docker image to EC2" \
          --instance-ids "$INSTANCE_ID" \
          --parameters '{"commands":["aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 648908580279.dkr.ecr.ap-south-1.amazonaws.com","docker pull 648908580279.dkr.ecr.ap-south-1.amazonaws.com/dev-env:latest","docker stop dev-env || true","docker rm dev-env || true","docker run -d --name dev-env -p 5000:5000 648908580279.dkr.ecr.ap-south-1.amazonaws.com/dev-env:latest"]}' \
          --region ap-south-1

artifacts:
  files:
    - appspec.yml
    - scripts/*
    - Dockerfile
    - requirements.txt
    - app.py
