version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
  pre_build:
    commands:
      - echo Pre-build stage...
  build:
    commands:
      - echo Zipping app files...
      - zip -r app.zip .
  post_build:
    commands:
      - echo Build completed.
artifacts:
  files:
    - app.zip
