version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt -t ./package

  build:
    commands:
      - echo Build phase...
      - echo Preparing files for deployment...

artifacts:
  files:
    - appspec.yml
    - scripts/**
    - package/**
    - app.py
