version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing AWS CLI and verifying credentials..."
      - pip install --upgrade awscli
      - aws sts get-caller-identity
      - aws configure set region ap-south-1
      - REGION=$(aws configure get region)
      - echo "Region is $REGION"

  build:
    commands:
      - echo "Starting EC2 deployment using SSM..."
      - echo "Looking for EC2 instance with tag Name=dev-AppServer..."
      
      # Describe EC2 instance and capture instance ID
      - INSTANCE_ID=$(aws ec2 describe-instances \
          --filters "Name=tag:Name,Values=dev-AppServer" \
          --query "Reservations[*].Instances[*].InstanceId" \
          --output text --region ap-south-1)

      # Check if INSTANCE_ID is empty
      - if [ -z "$INSTANCE_ID" ]; then echo "❌ ERROR: No EC2 instance found with tag Name=dev-AppServer"; exit 1; fi

      - echo "✅ Found EC2 Instance ID: $INSTANCE_ID"

      # Send command to EC2 using SSM
      - echo "Sending deployment command via SSM..."
      - aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --instance-ids "$INSTANCE_ID" \
          --comment "Deployment triggered from CodeBuild" \
          --parameters 'commands=["cd /home/ec2-user/myapp && git pull origin dev && chmod +x deploy.sh && ./deploy.sh"]' \
          --region ap-south-1

artifacts:
  files:
    - '**/*'
