version: 0.2

phases:
  install:
    commands:
      - echo Installing...
  build:
    commands:
      - echo Build step...
artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - Dockerfile
    - app.py
