version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing...
  build:
    commands:
      - echo Build started on `date`
      - zip -r app.zip *  # example
artifacts:
  files:
    - app.zip
